// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerRatings.Models;

#nullable disable

namespace PlayerRatings.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107055553_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlayerRatings.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthYearValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Residence")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PlayerRatings.Models.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("IX_Invite_InvitedById");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("PlayerRatings.Models.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("League");
                });

            modelBuilder.Entity("PlayerRatings.Models.LeaguePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBlocked");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_LeaguePlayer_LeagueId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LeaguePlayer_UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .HasDatabaseName("IX_LeaguePlayer_LeagueId_UserId");

                    b.ToTable("LeaguePlayer");
                });

            modelBuilder.Entity("PlayerRatings.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Factor")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstPlayerScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameRecord")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchResultPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondPlayerScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Match_Date");

                    b.HasIndex("FirstPlayerId")
                        .HasDatabaseName("IX_Match_FirstPlayerId");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_Match_LeagueId");

                    b.HasIndex("SecondPlayerId")
                        .HasDatabaseName("IX_Match_SecondPlayerId");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("IX_Match_TournamentId");

                    b.HasIndex("LeagueId", "Date")
                        .HasDatabaseName("IX_Match_LeagueId_Date");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("PlayerRatings.Models.PlayerRanking", b =>
                {
                    b.Property<Guid>("RankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RankingDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankingNote")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("RankingId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_PlayerRanking_PlayerId");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("IX_PlayerRanking_TournamentId");

                    b.ToTable("PlayerRanking");
                });

            modelBuilder.Entity("PlayerRatings.Models.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalLinks")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Factor")
                        .HasColumnType("REAL");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordinal")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandingsPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsFemaleAward")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsPersonalAward")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTeamAward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TournamentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_Tournament_LeagueId");

                    b.HasIndex("LeagueId", "StartDate")
                        .HasDatabaseName("IX_Tournament_LeagueId_StartDate");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("PlayerRatings.Models.TournamentPlayer", b =>
                {
                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("FemaleAwardPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FemalePosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("TournamentId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_TournamentPlayer_PlayerId");

                    b.HasIndex("PromotionId");

                    b.ToTable("TournamentPlayer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerRatings.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerRatings.Models.Invite", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("PlayerRatings.Models.ApplicationUser", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById");

                    b.Navigation("CreatedUser");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("PlayerRatings.Models.League", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PlayerRatings.Models.LeaguePlayer", b =>
                {
                    b.HasOne("PlayerRatings.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerRatings.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayerRatings.Models.Match", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("PlayerRatings.Models.ApplicationUser", "FirstPlayer")
                        .WithMany()
                        .HasForeignKey("FirstPlayerId");

                    b.HasOne("PlayerRatings.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerRatings.Models.ApplicationUser", "SecondPlayer")
                        .WithMany()
                        .HasForeignKey("SecondPlayerId");

                    b.HasOne("PlayerRatings.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FirstPlayer");

                    b.Navigation("League");

                    b.Navigation("SecondPlayer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PlayerRatings.Models.PlayerRanking", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", "Player")
                        .WithMany("Rankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerRatings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId");

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PlayerRatings.Models.Tournament", b =>
                {
                    b.HasOne("PlayerRatings.Models.League", "League")
                        .WithMany("Tournaments")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("PlayerRatings.Models.TournamentPlayer", b =>
                {
                    b.HasOne("PlayerRatings.Models.ApplicationUser", "Player")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerRatings.Models.PlayerRanking", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.HasOne("PlayerRatings.Models.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Promotion");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PlayerRatings.Models.ApplicationUser", b =>
                {
                    b.Navigation("Rankings");

                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("PlayerRatings.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("PlayerRatings.Models.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
